// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -source=services.go -destination=mock/services_mock.go -package=portsmock
//

// Package portsmock is a generated GoMock package.
package portsmock

import (
	context "context"
	reflect "reflect"

	models "github.com/arvaliullin/metrics-collection-service/internal/model"
	ports "github.com/arvaliullin/metrics-collection-service/internal/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsCollector is a mock of MetricsCollector interface.
type MockMetricsCollector struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsCollectorMockRecorder
	isgomock struct{}
}

// MockMetricsCollectorMockRecorder is the mock recorder for MockMetricsCollector.
type MockMetricsCollectorMockRecorder struct {
	mock *MockMetricsCollector
}

// NewMockMetricsCollector creates a new mock instance.
func NewMockMetricsCollector(ctrl *gomock.Controller) *MockMetricsCollector {
	mock := &MockMetricsCollector{ctrl: ctrl}
	mock.recorder = &MockMetricsCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsCollector) EXPECT() *MockMetricsCollectorMockRecorder {
	return m.recorder
}

// CollectGopsutilMetrics mocks base method.
func (m *MockMetricsCollector) CollectGopsutilMetrics(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectGopsutilMetrics", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CollectGopsutilMetrics indicates an expected call of CollectGopsutilMetrics.
func (mr *MockMetricsCollectorMockRecorder) CollectGopsutilMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectGopsutilMetrics", reflect.TypeOf((*MockMetricsCollector)(nil).CollectGopsutilMetrics), ctx)
}

// CollectRuntimeMetrics mocks base method.
func (m *MockMetricsCollector) CollectRuntimeMetrics(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectRuntimeMetrics", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CollectRuntimeMetrics indicates an expected call of CollectRuntimeMetrics.
func (mr *MockMetricsCollectorMockRecorder) CollectRuntimeMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectRuntimeMetrics", reflect.TypeOf((*MockMetricsCollector)(nil).CollectRuntimeMetrics), ctx)
}

// MockMetricsReporter is a mock of MetricsReporter interface.
type MockMetricsReporter struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsReporterMockRecorder
	isgomock struct{}
}

// MockMetricsReporterMockRecorder is the mock recorder for MockMetricsReporter.
type MockMetricsReporterMockRecorder struct {
	mock *MockMetricsReporter
}

// NewMockMetricsReporter creates a new mock instance.
func NewMockMetricsReporter(ctrl *gomock.Controller) *MockMetricsReporter {
	mock := &MockMetricsReporter{ctrl: ctrl}
	mock.recorder = &MockMetricsReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsReporter) EXPECT() *MockMetricsReporterMockRecorder {
	return m.recorder
}

// BuildBatch mocks base method.
func (m *MockMetricsReporter) BuildBatch(ctx context.Context) ([]models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildBatch", ctx)
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildBatch indicates an expected call of BuildBatch.
func (mr *MockMetricsReporterMockRecorder) BuildBatch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildBatch", reflect.TypeOf((*MockMetricsReporter)(nil).BuildBatch), ctx)
}

// ReportBatch mocks base method.
func (m *MockMetricsReporter) ReportBatch(ctx context.Context, metrics []models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportBatch", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportBatch indicates an expected call of ReportBatch.
func (mr *MockMetricsReporterMockRecorder) ReportBatch(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportBatch", reflect.TypeOf((*MockMetricsReporter)(nil).ReportBatch), ctx, metrics)
}

// MockMetricsSender is a mock of MetricsSender interface.
type MockMetricsSender struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsSenderMockRecorder
	isgomock struct{}
}

// MockMetricsSenderMockRecorder is the mock recorder for MockMetricsSender.
type MockMetricsSenderMockRecorder struct {
	mock *MockMetricsSender
}

// NewMockMetricsSender creates a new mock instance.
func NewMockMetricsSender(ctrl *gomock.Controller) *MockMetricsSender {
	mock := &MockMetricsSender{ctrl: ctrl}
	mock.recorder = &MockMetricsSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsSender) EXPECT() *MockMetricsSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockMetricsSender) Send(ctx context.Context, metrics []models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMetricsSenderMockRecorder) Send(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMetricsSender)(nil).Send), ctx, metrics)
}

// MockMetricsService is a mock of MetricsService interface.
type MockMetricsService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsServiceMockRecorder
	isgomock struct{}
}

// MockMetricsServiceMockRecorder is the mock recorder for MockMetricsService.
type MockMetricsServiceMockRecorder struct {
	mock *MockMetricsService
}

// NewMockMetricsService creates a new mock instance.
func NewMockMetricsService(ctrl *gomock.Controller) *MockMetricsService {
	mock := &MockMetricsService{ctrl: ctrl}
	mock.recorder = &MockMetricsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsService) EXPECT() *MockMetricsServiceMockRecorder {
	return m.recorder
}

// StartCollection mocks base method.
func (m *MockMetricsService) StartCollection(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartCollection", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartCollection indicates an expected call of StartCollection.
func (mr *MockMetricsServiceMockRecorder) StartCollection(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCollection", reflect.TypeOf((*MockMetricsService)(nil).StartCollection), ctx)
}

// StartReporting mocks base method.
func (m *MockMetricsService) StartReporting(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartReporting", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartReporting indicates an expected call of StartReporting.
func (mr *MockMetricsServiceMockRecorder) StartReporting(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartReporting", reflect.TypeOf((*MockMetricsService)(nil).StartReporting), ctx)
}

// MockAuditNotifier is a mock of AuditNotifier interface.
type MockAuditNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockAuditNotifierMockRecorder
	isgomock struct{}
}

// MockAuditNotifierMockRecorder is the mock recorder for MockAuditNotifier.
type MockAuditNotifierMockRecorder struct {
	mock *MockAuditNotifier
}

// NewMockAuditNotifier creates a new mock instance.
func NewMockAuditNotifier(ctrl *gomock.Controller) *MockAuditNotifier {
	mock := &MockAuditNotifier{ctrl: ctrl}
	mock.recorder = &MockAuditNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditNotifier) EXPECT() *MockAuditNotifierMockRecorder {
	return m.recorder
}

// NotifyAll mocks base method.
func (m *MockAuditNotifier) NotifyAll(event models.AuditEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyAll", event)
}

// NotifyAll indicates an expected call of NotifyAll.
func (mr *MockAuditNotifierMockRecorder) NotifyAll(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyAll", reflect.TypeOf((*MockAuditNotifier)(nil).NotifyAll), event)
}

// Subscribe mocks base method.
func (m *MockAuditNotifier) Subscribe(observer ports.AuditObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Subscribe", observer)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockAuditNotifierMockRecorder) Subscribe(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockAuditNotifier)(nil).Subscribe), observer)
}

// Unsubscribe mocks base method.
func (m *MockAuditNotifier) Unsubscribe(observer ports.AuditObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", observer)
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockAuditNotifierMockRecorder) Unsubscribe(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockAuditNotifier)(nil).Unsubscribe), observer)
}

// MockAuditObserver is a mock of AuditObserver interface.
type MockAuditObserver struct {
	ctrl     *gomock.Controller
	recorder *MockAuditObserverMockRecorder
	isgomock struct{}
}

// MockAuditObserverMockRecorder is the mock recorder for MockAuditObserver.
type MockAuditObserverMockRecorder struct {
	mock *MockAuditObserver
}

// NewMockAuditObserver creates a new mock instance.
func NewMockAuditObserver(ctrl *gomock.Controller) *MockAuditObserver {
	mock := &MockAuditObserver{ctrl: ctrl}
	mock.recorder = &MockAuditObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditObserver) EXPECT() *MockAuditObserverMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockAuditObserver) Notify(event models.AuditEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockAuditObserverMockRecorder) Notify(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockAuditObserver)(nil).Notify), event)
}

// MockServerMetricsService is a mock of ServerMetricsService interface.
type MockServerMetricsService struct {
	ctrl     *gomock.Controller
	recorder *MockServerMetricsServiceMockRecorder
	isgomock struct{}
}

// MockServerMetricsServiceMockRecorder is the mock recorder for MockServerMetricsService.
type MockServerMetricsServiceMockRecorder struct {
	mock *MockServerMetricsService
}

// NewMockServerMetricsService creates a new mock instance.
func NewMockServerMetricsService(ctrl *gomock.Controller) *MockServerMetricsService {
	mock := &MockServerMetricsService{ctrl: ctrl}
	mock.recorder = &MockServerMetricsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerMetricsService) EXPECT() *MockServerMetricsServiceMockRecorder {
	return m.recorder
}

// BatchUpdate mocks base method.
func (m *MockServerMetricsService) BatchUpdate(ctx context.Context, metrics []models.Metrics) ([]models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ctx, metrics)
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockServerMetricsServiceMockRecorder) BatchUpdate(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockServerMetricsService)(nil).BatchUpdate), ctx, metrics)
}

// GetAllMetrics mocks base method.
func (m *MockServerMetricsService) GetAllMetrics(ctx context.Context) ([]models.Metrics, []models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMetrics", ctx)
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].([]models.Metrics)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllMetrics indicates an expected call of GetAllMetrics.
func (mr *MockServerMetricsServiceMockRecorder) GetAllMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMetrics", reflect.TypeOf((*MockServerMetricsService)(nil).GetAllMetrics), ctx)
}

// GetCounter mocks base method.
func (m *MockServerMetricsService) GetCounter(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockServerMetricsServiceMockRecorder) GetCounter(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockServerMetricsService)(nil).GetCounter), ctx, id)
}

// GetGauge mocks base method.
func (m *MockServerMetricsService) GetGauge(ctx context.Context, id string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGauge", ctx, id)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGauge indicates an expected call of GetGauge.
func (mr *MockServerMetricsServiceMockRecorder) GetGauge(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGauge", reflect.TypeOf((*MockServerMetricsService)(nil).GetGauge), ctx, id)
}

// GetMetric mocks base method.
func (m *MockServerMetricsService) GetMetric(ctx context.Context, metric models.Metrics) (models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetric", ctx, metric)
	ret0, _ := ret[0].(models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetric indicates an expected call of GetMetric.
func (mr *MockServerMetricsServiceMockRecorder) GetMetric(ctx, metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetric", reflect.TypeOf((*MockServerMetricsService)(nil).GetMetric), ctx, metric)
}

// UpdateCounter mocks base method.
func (m *MockServerMetricsService) UpdateCounter(ctx context.Context, id string, delta int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCounter", ctx, id, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCounter indicates an expected call of UpdateCounter.
func (mr *MockServerMetricsServiceMockRecorder) UpdateCounter(ctx, id, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCounter", reflect.TypeOf((*MockServerMetricsService)(nil).UpdateCounter), ctx, id, delta)
}

// UpdateGauge mocks base method.
func (m *MockServerMetricsService) UpdateGauge(ctx context.Context, id string, value float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGauge", ctx, id, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGauge indicates an expected call of UpdateGauge.
func (mr *MockServerMetricsServiceMockRecorder) UpdateGauge(ctx, id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGauge", reflect.TypeOf((*MockServerMetricsService)(nil).UpdateGauge), ctx, id, value)
}

// UpdateMetric mocks base method.
func (m *MockServerMetricsService) UpdateMetric(ctx context.Context, metric models.Metrics) (models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetric", ctx, metric)
	ret0, _ := ret[0].(models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMetric indicates an expected call of UpdateMetric.
func (mr *MockServerMetricsServiceMockRecorder) UpdateMetric(ctx, metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetric", reflect.TypeOf((*MockServerMetricsService)(nil).UpdateMetric), ctx, metric)
}
