// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -source=services.go -destination=mock/services_mock.go -package=portsmock
//

// Package portsmock is a generated GoMock package.
package portsmock

import (
	context "context"
	reflect "reflect"

	models "github.com/arvaliullin/metrics-collection-service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsCollector is a mock of MetricsCollector interface.
type MockMetricsCollector struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsCollectorMockRecorder
	isgomock struct{}
}

// MockMetricsCollectorMockRecorder is the mock recorder for MockMetricsCollector.
type MockMetricsCollectorMockRecorder struct {
	mock *MockMetricsCollector
}

// NewMockMetricsCollector creates a new mock instance.
func NewMockMetricsCollector(ctrl *gomock.Controller) *MockMetricsCollector {
	mock := &MockMetricsCollector{ctrl: ctrl}
	mock.recorder = &MockMetricsCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsCollector) EXPECT() *MockMetricsCollectorMockRecorder {
	return m.recorder
}

// CollectGopsutilMetrics mocks base method.
func (m *MockMetricsCollector) CollectGopsutilMetrics(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectGopsutilMetrics", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CollectGopsutilMetrics indicates an expected call of CollectGopsutilMetrics.
func (mr *MockMetricsCollectorMockRecorder) CollectGopsutilMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectGopsutilMetrics", reflect.TypeOf((*MockMetricsCollector)(nil).CollectGopsutilMetrics), ctx)
}

// CollectRuntimeMetrics mocks base method.
func (m *MockMetricsCollector) CollectRuntimeMetrics(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectRuntimeMetrics", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CollectRuntimeMetrics indicates an expected call of CollectRuntimeMetrics.
func (mr *MockMetricsCollectorMockRecorder) CollectRuntimeMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectRuntimeMetrics", reflect.TypeOf((*MockMetricsCollector)(nil).CollectRuntimeMetrics), ctx)
}

// MockMetricsReporter is a mock of MetricsReporter interface.
type MockMetricsReporter struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsReporterMockRecorder
	isgomock struct{}
}

// MockMetricsReporterMockRecorder is the mock recorder for MockMetricsReporter.
type MockMetricsReporterMockRecorder struct {
	mock *MockMetricsReporter
}

// NewMockMetricsReporter creates a new mock instance.
func NewMockMetricsReporter(ctrl *gomock.Controller) *MockMetricsReporter {
	mock := &MockMetricsReporter{ctrl: ctrl}
	mock.recorder = &MockMetricsReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsReporter) EXPECT() *MockMetricsReporterMockRecorder {
	return m.recorder
}

// BuildBatch mocks base method.
func (m *MockMetricsReporter) BuildBatch(ctx context.Context) ([]models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildBatch", ctx)
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildBatch indicates an expected call of BuildBatch.
func (mr *MockMetricsReporterMockRecorder) BuildBatch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildBatch", reflect.TypeOf((*MockMetricsReporter)(nil).BuildBatch), ctx)
}

// ReportBatch mocks base method.
func (m *MockMetricsReporter) ReportBatch(ctx context.Context, metrics []models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportBatch", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportBatch indicates an expected call of ReportBatch.
func (mr *MockMetricsReporterMockRecorder) ReportBatch(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportBatch", reflect.TypeOf((*MockMetricsReporter)(nil).ReportBatch), ctx, metrics)
}

// MockMetricsSender is a mock of MetricsSender interface.
type MockMetricsSender struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsSenderMockRecorder
	isgomock struct{}
}

// MockMetricsSenderMockRecorder is the mock recorder for MockMetricsSender.
type MockMetricsSenderMockRecorder struct {
	mock *MockMetricsSender
}

// NewMockMetricsSender creates a new mock instance.
func NewMockMetricsSender(ctrl *gomock.Controller) *MockMetricsSender {
	mock := &MockMetricsSender{ctrl: ctrl}
	mock.recorder = &MockMetricsSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsSender) EXPECT() *MockMetricsSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockMetricsSender) Send(ctx context.Context, metrics []models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMetricsSenderMockRecorder) Send(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMetricsSender)(nil).Send), ctx, metrics)
}

// MockMetricsService is a mock of MetricsService interface.
type MockMetricsService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsServiceMockRecorder
	isgomock struct{}
}

// MockMetricsServiceMockRecorder is the mock recorder for MockMetricsService.
type MockMetricsServiceMockRecorder struct {
	mock *MockMetricsService
}

// NewMockMetricsService creates a new mock instance.
func NewMockMetricsService(ctrl *gomock.Controller) *MockMetricsService {
	mock := &MockMetricsService{ctrl: ctrl}
	mock.recorder = &MockMetricsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsService) EXPECT() *MockMetricsServiceMockRecorder {
	return m.recorder
}

// StartCollection mocks base method.
func (m *MockMetricsService) StartCollection(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartCollection", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartCollection indicates an expected call of StartCollection.
func (mr *MockMetricsServiceMockRecorder) StartCollection(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCollection", reflect.TypeOf((*MockMetricsService)(nil).StartCollection), ctx)
}

// StartReporting mocks base method.
func (m *MockMetricsService) StartReporting(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartReporting", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartReporting indicates an expected call of StartReporting.
func (mr *MockMetricsServiceMockRecorder) StartReporting(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartReporting", reflect.TypeOf((*MockMetricsService)(nil).StartReporting), ctx)
}
