version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: build/server.Dockerfile
    command: ["server", "-a", "0.0.0.0:8080"]
    ports:
      - "8080:8080"
    restart: unless-stopped

  agent:
    build:
      context: .
      dockerfile: build/agent.Dockerfile
    command: ["agent", "-a", "http://server:8080", "-r", "10", "-p", "2"]
    depends_on:
      - server
    restart: unless-stopped
