services:
  server:
    build:
      context: .
      dockerfile: build/server.Dockerfile
    ports:
      - "8080:8080"
      - "3200:3200"
    volumes:
      - ./keys:/keys:ro
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ADDRESS: "0.0.0.0:8080"
      GRPC_ADDRESS: ":3200"
      DATABASE_DSN: postgres://postgres_user:postgres_password@postgres:5432/postgres_db?sslmode=disable
      KEY: secret-key
      CRYPTO_KEY: /keys/private.pem
    restart: unless-stopped
    networks:
      - metrics-network

  agent:
    build:
      context: .
      dockerfile: build/agent.Dockerfile
    volumes:
      - ./keys:/keys:ro
    depends_on:
      - server
    environment:
      ADDRESS: http://server:8080
      GRPC_ADDRESS: server:3200
      POLL_INTERVAL: 2
      REPORT_INTERVAL: 3
      KEY: secret-key
      CRYPTO_KEY: /keys/public.pem
    restart: unless-stopped
    networks:
      - metrics-network

  postgres:
    image: postgres:17-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - metrics-network

  adminer:
    image: adminer:standalone
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - metrics-network

volumes:
  postgres-data:


networks:
  metrics-network:
    driver: bridge
