// Code generated by MockGen. DO NOT EDIT.
// Source: notifier.go
//
// Generated by this command:
//
//	mockgen -source=notifier.go -destination=mock/notifier_mock.go -package=auditmock
//

// Package auditmock is a generated GoMock package.
package auditmock

import (
	reflect "reflect"

	audit "github.com/arvaliullin/metrics-collection-service/internal/audit"
	models "github.com/arvaliullin/metrics-collection-service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// NotifyAll mocks base method.
func (m *MockNotifier) NotifyAll(event models.AuditEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyAll", event)
}

// NotifyAll indicates an expected call of NotifyAll.
func (mr *MockNotifierMockRecorder) NotifyAll(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyAll", reflect.TypeOf((*MockNotifier)(nil).NotifyAll), event)
}

// Subscribe mocks base method.
func (m *MockNotifier) Subscribe(observer audit.AuditObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Subscribe", observer)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockNotifierMockRecorder) Subscribe(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockNotifier)(nil).Subscribe), observer)
}

// Unsubscribe mocks base method.
func (m *MockNotifier) Unsubscribe(observer audit.AuditObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", observer)
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockNotifierMockRecorder) Unsubscribe(observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockNotifier)(nil).Unsubscribe), observer)
}
