// Code generated by MockGen. DO NOT EDIT.
// Source: observer.go
//
// Generated by this command:
//
//	mockgen -source=observer.go -destination=mock/observer_mock.go -package=auditmock
//

// Package auditmock is a generated GoMock package.
package auditmock

import (
	reflect "reflect"

	models "github.com/arvaliullin/metrics-collection-service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditObserver is a mock of AuditObserver interface.
type MockAuditObserver struct {
	ctrl     *gomock.Controller
	recorder *MockAuditObserverMockRecorder
	isgomock struct{}
}

// MockAuditObserverMockRecorder is the mock recorder for MockAuditObserver.
type MockAuditObserverMockRecorder struct {
	mock *MockAuditObserver
}

// NewMockAuditObserver creates a new mock instance.
func NewMockAuditObserver(ctrl *gomock.Controller) *MockAuditObserver {
	mock := &MockAuditObserver{ctrl: ctrl}
	mock.recorder = &MockAuditObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditObserver) EXPECT() *MockAuditObserverMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockAuditObserver) Notify(event models.AuditEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockAuditObserverMockRecorder) Notify(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockAuditObserver)(nil).Notify), event)
}
