// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go

// Package updatemock is a generated GoMock package.
package updatemock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricStorage is a mock of MetricStorage interface.
type MockMetricStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMetricStorageMockRecorder
}

// MockMetricStorageMockRecorder is the mock recorder for MockMetricStorage.
type MockMetricStorageMockRecorder struct {
	mock *MockMetricStorage
}

// NewMockMetricStorage creates a new mock instance.
func NewMockMetricStorage(ctrl *gomock.Controller) *MockMetricStorage {
	mock := &MockMetricStorage{ctrl: ctrl}
	mock.recorder = &MockMetricStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricStorage) EXPECT() *MockMetricStorageMockRecorder {
	return m.recorder
}

// AddCounter mocks base method.
func (m *MockMetricStorage) AddCounter(ctx context.Context, id string, newCounter int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCounter", ctx, id, newCounter)
}

// AddCounter indicates an expected call of AddCounter.
func (mr *MockMetricStorageMockRecorder) AddCounter(ctx, id, newCounter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCounter", reflect.TypeOf((*MockMetricStorage)(nil).AddCounter), ctx, id, newCounter)
}

// AddCounterValue mocks base method.
func (m *MockMetricStorage) AddCounterValue(ctx context.Context, id string, delta int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCounterValue", ctx, id, delta)
}

// AddCounterValue indicates an expected call of AddCounterValue.
func (mr *MockMetricStorageMockRecorder) AddCounterValue(ctx, id, delta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCounterValue", reflect.TypeOf((*MockMetricStorage)(nil).AddCounterValue), ctx, id, delta)
}

// GetCounter mocks base method.
func (m *MockMetricStorage) GetCounter(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockMetricStorageMockRecorder) GetCounter(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockMetricStorage)(nil).GetCounter), ctx, id)
}

// GetGauge mocks base method.
func (m *MockMetricStorage) GetGauge(ctx context.Context, id string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGauge", ctx, id)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGauge indicates an expected call of GetGauge.
func (mr *MockMetricStorageMockRecorder) GetGauge(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGauge", reflect.TypeOf((*MockMetricStorage)(nil).GetGauge), ctx, id)
}

// UpdateGauge mocks base method.
func (m *MockMetricStorage) UpdateGauge(ctx context.Context, id string, newGauge float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateGauge", ctx, id, newGauge)
}

// UpdateGauge indicates an expected call of UpdateGauge.
func (mr *MockMetricStorageMockRecorder) UpdateGauge(ctx, id, newGauge interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGauge", reflect.TypeOf((*MockMetricStorage)(nil).UpdateGauge), ctx, id, newGauge)
}
