// Code generated by reset. DO NOT EDIT.
//
// Generated by this command:
//
//	go run ./cmd/reset .
//
// Package models is a generated reset package.
package models

func (ae *AuditEvent) Reset() {
	if ae == nil {
		return
	}
	ae.TS = 0
	ae.Metrics = ae.Metrics[:0]
	ae.IPAddress = ""
}
