// Code generated by reset. DO NOT EDIT.
//
// Generated by this command:
//
//	go run ./cmd/reset .
//
// Package models is a generated reset package.
package models

func (mb *MetricsBatch) Reset() {
	if mb == nil {
		return
	}
	mb.Metrics = mb.Metrics[:0]
}
