// Code generated by reset. DO NOT EDIT.
//
// Generated by this command:
//
//	go run ./cmd/reset .
//
// Package models is a generated reset package.
package models

func (rs *ResetableStruct) Reset() {
	if rs == nil {
		return
	}
	rs.i = 0
	rs.str = ""
	if rs.strP != nil {
		*rs.strP = ""
	}
	rs.s = rs.s[:0]
	clear(rs.m)
	if rs.child != nil {
		rs.child.Reset()
	}
}
