package main

import (
	"go/ast"
	"go/format"
	"go/token"
	"strings"

	"golang.org/x/tools/go/packages"
)

// genHeaderCmd - строка команды в заголовке сгенерированного файла.
const genHeaderCmd = "//\tgo run ./cmd/reset .\n"

// generateFile формирует содержимое файла <исходный_файл>.gen.go для пакета и списка структур.
func generateFile(pkg *packages.Package, targets []*targetStruct) ([]byte, error) {
	pname := pkgName(pkg)
	decls := make([]ast.Decl, 0, len(targets))
	for _, t := range targets {
		recv := receiverName(t.TypeName.Obj().Name())
		body := generateResetBody(recv, t.Struct, pkg.Types)
		decls = append(decls, &ast.FuncDecl{
			Recv: &ast.FieldList{
				List: []*ast.Field{{
					Names: []*ast.Ident{{Name: recv}},
					Type:  &ast.StarExpr{X: &ast.Ident{Name: t.TypeName.Obj().Name()}},
				}},
			},
			Name: &ast.Ident{Name: "Reset"},
			Type: &ast.FuncType{Params: &ast.FieldList{}, Results: &ast.FieldList{}},
			Body: &ast.BlockStmt{List: body},
		})
	}
	f := &ast.File{
		Name:  &ast.Ident{Name: pname},
		Decls: decls,
	}
	var buf strings.Builder
	if err := format.Node(&buf, token.NewFileSet(), f); err != nil {
		return nil, err
	}
	header := "// Code generated by reset. DO NOT EDIT.\n" +
		"//\n" +
		"// Generated by this command:\n" +
		"//\n" +
		genHeaderCmd +
		"//\n" +
		"// Package " + pname + " is a generated reset package.\n"
	return format.Source(append([]byte(header), []byte(buf.String())...))
}
