package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/arvaliullin/metrics-collection-service/cmd/reset/discover"
	"github.com/arvaliullin/metrics-collection-service/cmd/reset/gen"
	"github.com/arvaliullin/metrics-collection-service/cmd/reset/scan"
	"github.com/arvaliullin/metrics-collection-service/cmd/reset/write"
)

func TestRun_integration(t *testing.T) {
	root := t.TempDir()
	pkgDir := filepath.Join(root, "pkg")
	if err := os.MkdirAll(pkgDir, 0755); err != nil {
		t.Fatal(err)
	}
	goMod := `module testmod
go 1.21
`
	mainGo := `package pkg

// generate:reset
type T struct {
	X int
}
`
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte(goMod), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "t.go"), []byte(mainGo), 0644); err != nil {
		t.Fatal(err)
	}

	n, errs := Run(root, discover.DefaultFinder{}, scan.DefaultScanner{}, gen.DefaultGenerator{}, write.OSWriter{})
	if len(errs) > 0 {
		t.Fatalf("Run failed: %v", errs)
	}
	if n != 1 {
		t.Fatalf("expected 1 file written, got %d", n)
	}

	genPath := filepath.Join(pkgDir, "t.gen.go")
	data, err := os.ReadFile(genPath)
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}
	code := string(data)
	if !strings.Contains(code, "func (t *T) Reset()") {
		t.Errorf("expected (t *T) Reset() in generated file:\n%s", code)
	}
	if !strings.Contains(code, "t.X = 0") {
		t.Errorf("expected t.X = 0 in generated file")
	}
	if !strings.Contains(code, "Code generated by reset") {
		t.Errorf("expected generated header in file")
	}
}
