// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go

// Package pingmock is a generated GoMock package.
package pingmock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPostgresRepository is a mock of PostgresRepository interface.
type MockPostgresRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPostgresRepositoryMockRecorder
}

// MockPostgresRepositoryMockRecorder is the mock recorder for MockPostgresRepository.
type MockPostgresRepositoryMockRecorder struct {
	mock *MockPostgresRepository
}

// NewMockPostgresRepository creates a new mock instance.
func NewMockPostgresRepository(ctrl *gomock.Controller) *MockPostgresRepository {
	mock := &MockPostgresRepository{ctrl: ctrl}
	mock.recorder = &MockPostgresRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgresRepository) EXPECT() *MockPostgresRepositoryMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockPostgresRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockPostgresRepositoryMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockPostgresRepository)(nil).Ping), ctx)
}
