// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go

// Package agentmock is a generated GoMock package.
package agentmock

import (
	context "context"
	reflect "reflect"

	models "github.com/arvaliullin/metrics-collection-service/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockMetricStorage is a mock of MetricStorage interface.
type MockMetricStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMetricStorageMockRecorder
}

// MockMetricStorageMockRecorder is the mock recorder for MockMetricStorage.
type MockMetricStorageMockRecorder struct {
	mock *MockMetricStorage
}

// NewMockMetricStorage creates a new mock instance.
func NewMockMetricStorage(ctrl *gomock.Controller) *MockMetricStorage {
	mock := &MockMetricStorage{ctrl: ctrl}
	mock.recorder = &MockMetricStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricStorage) EXPECT() *MockMetricStorageMockRecorder {
	return m.recorder
}

// AddCounter mocks base method.
func (m *MockMetricStorage) AddCounter(ctx context.Context, id string, newCounter int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCounter", ctx, id, newCounter)
}

// AddCounter indicates an expected call of AddCounter.
func (mr *MockMetricStorageMockRecorder) AddCounter(ctx, id, newCounter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCounter", reflect.TypeOf((*MockMetricStorage)(nil).AddCounter), ctx, id, newCounter)
}

// AllCounters mocks base method.
func (m *MockMetricStorage) AllCounters(ctx context.Context) []models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllCounters", ctx)
	ret0, _ := ret[0].([]models.Metrics)
	return ret0
}

// AllCounters indicates an expected call of AllCounters.
func (mr *MockMetricStorageMockRecorder) AllCounters(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllCounters", reflect.TypeOf((*MockMetricStorage)(nil).AllCounters), ctx)
}

// AllGauges mocks base method.
func (m *MockMetricStorage) AllGauges(ctx context.Context) []models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllGauges", ctx)
	ret0, _ := ret[0].([]models.Metrics)
	return ret0
}

// AllGauges indicates an expected call of AllGauges.
func (mr *MockMetricStorageMockRecorder) AllGauges(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllGauges", reflect.TypeOf((*MockMetricStorage)(nil).AllGauges), ctx)
}

// ResetCounter mocks base method.
func (m *MockMetricStorage) ResetCounter(ctx context.Context, id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResetCounter", ctx, id)
}

// ResetCounter indicates an expected call of ResetCounter.
func (mr *MockMetricStorageMockRecorder) ResetCounter(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetCounter", reflect.TypeOf((*MockMetricStorage)(nil).ResetCounter), ctx, id)
}

// UpdateGauge mocks base method.
func (m *MockMetricStorage) UpdateGauge(ctx context.Context, id string, newGauge float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateGauge", ctx, id, newGauge)
}

// UpdateGauge indicates an expected call of UpdateGauge.
func (mr *MockMetricStorageMockRecorder) UpdateGauge(ctx, id, newGauge interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGauge", reflect.TypeOf((*MockMetricStorage)(nil).UpdateGauge), ctx, id, newGauge)
}
