// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go

// Package htmlmock is a generated GoMock package.
package htmlmock

import (
	context "context"
	reflect "reflect"

	models "github.com/arvaliullin/metrics-collection-service/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockMetricStorage is a mock of MetricStorage interface.
type MockMetricStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMetricStorageMockRecorder
}

// MockMetricStorageMockRecorder is the mock recorder for MockMetricStorage.
type MockMetricStorageMockRecorder struct {
	mock *MockMetricStorage
}

// NewMockMetricStorage creates a new mock instance.
func NewMockMetricStorage(ctrl *gomock.Controller) *MockMetricStorage {
	mock := &MockMetricStorage{ctrl: ctrl}
	mock.recorder = &MockMetricStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricStorage) EXPECT() *MockMetricStorageMockRecorder {
	return m.recorder
}

// AllCounters mocks base method.
func (m *MockMetricStorage) AllCounters(ctx context.Context) []models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllCounters", ctx)
	ret0, _ := ret[0].([]models.Metrics)
	return ret0
}

// AllCounters indicates an expected call of AllCounters.
func (mr *MockMetricStorageMockRecorder) AllCounters(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllCounters", reflect.TypeOf((*MockMetricStorage)(nil).AllCounters), ctx)
}

// AllGauges mocks base method.
func (m *MockMetricStorage) AllGauges(ctx context.Context) []models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllGauges", ctx)
	ret0, _ := ret[0].([]models.Metrics)
	return ret0
}

// AllGauges indicates an expected call of AllGauges.
func (mr *MockMetricStorageMockRecorder) AllGauges(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllGauges", reflect.TypeOf((*MockMetricStorage)(nil).AllGauges), ctx)
}
