// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go

// Package server_mock is a generated GoMock package.
package server_mock

import (
	context "context"
	reflect "reflect"

	models "github.com/arvaliullin/metrics-collection-service/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockMetricStorage is a mock of MetricStorage interface.
type MockMetricStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMetricStorageMockRecorder
}

// MockMetricStorageMockRecorder is the mock recorder for MockMetricStorage.
type MockMetricStorageMockRecorder struct {
	mock *MockMetricStorage
}

// NewMockMetricStorage creates a new mock instance.
func NewMockMetricStorage(ctrl *gomock.Controller) *MockMetricStorage {
	mock := &MockMetricStorage{ctrl: ctrl}
	mock.recorder = &MockMetricStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricStorage) EXPECT() *MockMetricStorageMockRecorder {
	return m.recorder
}

// AddCounter mocks base method.
func (m *MockMetricStorage) AddCounter(ctx context.Context, id string, newCounter int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCounter", ctx, id, newCounter)
}

// AddCounter indicates an expected call of AddCounter.
func (mr *MockMetricStorageMockRecorder) AddCounter(ctx, id, newCounter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCounter", reflect.TypeOf((*MockMetricStorage)(nil).AddCounter), ctx, id, newCounter)
}

// AddCounterValue mocks base method.
func (m *MockMetricStorage) AddCounterValue(ctx context.Context, id string, delta int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCounterValue", ctx, id, delta)
}

// AddCounterValue indicates an expected call of AddCounterValue.
func (mr *MockMetricStorageMockRecorder) AddCounterValue(ctx, id, delta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCounterValue", reflect.TypeOf((*MockMetricStorage)(nil).AddCounterValue), ctx, id, delta)
}

// AllCounters mocks base method.
func (m *MockMetricStorage) AllCounters(ctx context.Context) []models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllCounters", ctx)
	ret0, _ := ret[0].([]models.Metrics)
	return ret0
}

// AllCounters indicates an expected call of AllCounters.
func (mr *MockMetricStorageMockRecorder) AllCounters(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllCounters", reflect.TypeOf((*MockMetricStorage)(nil).AllCounters), ctx)
}

// AllGauges mocks base method.
func (m *MockMetricStorage) AllGauges(ctx context.Context) []models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllGauges", ctx)
	ret0, _ := ret[0].([]models.Metrics)
	return ret0
}

// AllGauges indicates an expected call of AllGauges.
func (mr *MockMetricStorageMockRecorder) AllGauges(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllGauges", reflect.TypeOf((*MockMetricStorage)(nil).AllGauges), ctx)
}

// BatchUpdate mocks base method.
func (m *MockMetricStorage) BatchUpdate(ctx context.Context, metrics []models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockMetricStorageMockRecorder) BatchUpdate(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockMetricStorage)(nil).BatchUpdate), ctx, metrics)
}

// GetCounter mocks base method.
func (m *MockMetricStorage) GetCounter(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockMetricStorageMockRecorder) GetCounter(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockMetricStorage)(nil).GetCounter), ctx, id)
}

// GetGauge mocks base method.
func (m *MockMetricStorage) GetGauge(ctx context.Context, id string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGauge", ctx, id)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGauge indicates an expected call of GetGauge.
func (mr *MockMetricStorageMockRecorder) GetGauge(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGauge", reflect.TypeOf((*MockMetricStorage)(nil).GetGauge), ctx, id)
}

// Ping mocks base method.
func (m *MockMetricStorage) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockMetricStorageMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockMetricStorage)(nil).Ping), ctx)
}

// UpdateGauge mocks base method.
func (m *MockMetricStorage) UpdateGauge(ctx context.Context, id string, newGauge float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateGauge", ctx, id, newGauge)
}

// UpdateGauge indicates an expected call of UpdateGauge.
func (mr *MockMetricStorageMockRecorder) UpdateGauge(ctx, id, newGauge interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGauge", reflect.TypeOf((*MockMetricStorage)(nil).UpdateGauge), ctx, id, newGauge)
}
